#ifndef __BADENGINE_MOUSEBUTTON_H__
#define __BADENGINE_MOUSEBUTTON_H__

namespace BadEngine {
	enum MouseButton {
		MOUSE_BUTTON_LEFT = 1,
		MOUSE_BUTTON_MIDDLE,
		MOUSE_BUTTON_RIGHT,
		MOUSE_BUTTON_WHEELUP,
		MOUSE_BUTTON_WHEELDOWN,
		MOUSE_BUTTON_X1,
		MOUSE_BUTTON_X2
	};
};

#endif // __BADENGINE_MOUSEBUTTON_H__
